# В корне проекта PostgresDemo/
FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /src

# Копируем файлы проекта и восстанавливаем зависимости
COPY src/Presentation/PatientDemo.WebApi/PatientDemo.WebApi.csproj PatientDemo.WebApi/
RUN dotnet restore "PatientDemo.WebApi/PatientDemo.WebApi.csproj"

# Копируем остальные файлы и собираем проект
COPY src/Presentation/PatientDemo.WebApi/ PatientDemo.WebApi/
WORKDIR /src/PatientDemo.WebApi
RUN dotnet publish -c Release -o /app/publish

# Создаем образ для запуска
FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS runtime
WORKDIR /app
EXPOSE 80
EXPOSE 443

COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "PatientDemo.WebApi.dll"]