// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PatientDemo.Persistence.Data;

#nullable disable

namespace PatientDemo.Persistence.Migrations
{
    [DbContext(typeof(PatientDemoDbContext))]
    [Migration("20260227071427_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PatientDemo.Domain.Entities.HumanName", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<string>("Family")
                        .IsRequired()
                        .HasColumnType("varchar(100)")
                        .HasColumnName("FAMILY")
                        .HasColumnOrder(2);

                    b.PrimitiveCollection<string[]>("Given")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(30)[]")
                        .HasDefaultValue(new string[0])
                        .HasColumnName("GIVEN")
                        .HasColumnOrder(3);

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid");

                    b.Property<string>("Use")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(20)")
                        .HasDefaultValue("official")
                        .HasColumnName("USE")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.HasIndex("PatientId")
                        .IsUnique();

                    b.ToTable("HUMAN_NAMES", (string)null);
                });

            modelBuilder.Entity("PatientDemo.Domain.Entities.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("ID")
                        .HasColumnOrder(0);

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("ACTIVE")
                        .HasColumnOrder(3);

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date")
                        .HasColumnName("BIRTH_DATE")
                        .HasColumnOrder(2);

                    b.Property<string>("Gender")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("varchar(10)")
                        .HasDefaultValue("Unknown")
                        .HasColumnName("GENDER")
                        .HasColumnOrder(1);

                    b.HasKey("Id");

                    b.HasIndex("BirthDate");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("PATIENTS", (string)null);
                });

            modelBuilder.Entity("PatientDemo.Domain.Entities.HumanName", b =>
                {
                    b.HasOne("PatientDemo.Domain.Entities.Patient", "Patient")
                        .WithOne("Name")
                        .HasForeignKey("PatientDemo.Domain.Entities.HumanName", "PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PatientDemo.Domain.Entities.Patient", b =>
                {
                    b.Navigation("Name");
                });
#pragma warning restore 612, 618
        }
    }
}
